### ISSUE TITLE
How to win?

### ISSUE THREAD

**Issue by Randommood** [Randommood/thoughtstradamus#1]
What do we consider a winning Thoughtleader term for 2017?
Possible options:
- Term mentioned in a talk
- Term featured in hacker news
- Person with over 2k Twitter followers use it
  ...

**Comment by OleMchls** [comment]
What's the price though?

**Comment by griffio** [comment]
I am keeping an eye on svelte - The magical disappearing UI framework https://svelte.technology
https://svelte.technology/blog/frameworks-without-the-framework/
I can't believe our crystal balls didn't predict "frameworkless" 🎱 
It's been getting a lot of tweets and callouts for a whole week now. I know that's a long time in Javascript tech.

**Comment by griffio** [comment]
https://opensource.googleblog.com/2017/01/grumpy-go-running-python.html
We may see more language overlays on Go in the future 🚀  . I was guessing it would be something like elixir -> go

**Comment by sdboyer** [comment]
jfc how did we miss frameworkless
